DBA-1021
Made batch reinder more resilient. Added cronjob to restart repo pods every day at 5am UTC. Add kubectl diff to helm_upgrade for when its run with dry run and debug enabled in order to see the differences more clearly.

diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -127,6 +127,10 @@ tasks:
           DEBUG_FLAG: "{{.DEBUG_FLAG}}"
           ATOMIC_FLAG: "{{.ATOMIC_FLAG}}"
           DRY_RUN_FLAG: "{{.DRY_RUN_FLAG}}"
+      - task: helm_dryrun_diff
+        vars:
+          DEBUG: "{{.DEBUG}}"
+          DRY_RUN: "{{.DRY_RUN}}"
       - task: reset_allowlist
     silent: true
 
@@ -184,6 +188,30 @@ tasks:
         echo "Chart version: $(helm list -n {{.NAMESPACE}} | grep $RELEASE_NAME | awk '{print $9}')"
         echo "ACS Version: $(helm list -n {{.NAMESPACE}} | grep $RELEASE_NAME | awk '{print $10}')"
         echo " "
+
+  helm_dryrun_diff:
+    internal: true
+    dir: ./kustomize/{{.ENV}}
+    cmds:
+      - |
+        # to run diff it must have the DEBUG flag set to true and DRY_RUN to true
+        # as diff needs the resources.yaml file which is generated by helm but deleted 
+        # after the upgrade unless it is run with debug on
+        if {{.DEBUG}} && {{.DRY_RUN}}; then
+          echo "***** Comparing Helm template with live cluster *****"
+          export KUBECTL_EXTERNAL_DIFF='diff -u --color=always'
+          set +e
+          kubectl diff  -n {{.NAMESPACE}} -k .
+          ec=$?
+          set -e
+          if [ $ec -gt 1 ]; then
+            echo "kubectl diff failed with exit code $ec" >&2
+            exit $ec
+          fi
+          echo "***** Finished comparing Helm template with live cluster *****"
+        else
+          echo "Skipping helm diff as DEBUG and DRY_RUN are not both set to true"
+        fi
 
   reset_allowlist:
     internal: true
