Update Taskfile.yml
Amend task reindex_by_id to have optional param to specify if content should be reindexed and to scale up pods if reindexing more than 100000 docs.
Amend task reindex_by_date to have optional param to specify if content should be reindexed and scale up pods.
Added cleanup_unused_reindex_configmaps task to delete old configmaps which should be deleted (otherwise creating a new one for the same id or date range when reindexing will fail).
Added restart_deployments task to do a rolling restart of all deployments so that changes to configmaps can be applied.
Added reindex_scale_up task to only scale up the repo and tika pods by using their HPA configs (set the minReplicas = maxReplicas).
Added reindex_scale_down task to only scale down the repo and tika pods by using their HPA configs (set the minReplicas back to their default).
Added scale_up_deployments task to scale up all ACS deployments based on config file defaults (to be used after shutting them down).
Added scale_down_deployments task to effectively shut down all deployments by setting replicas=0

diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -42,6 +42,16 @@ vars:
   DRY_RUN_FLAG:
     sh: if [ "{{.DRY_RUN}}" = "true" ]; then echo "--dry-run"; else echo ""; fi
   CHART_VERSION: "7.0.3"
+  RELEASE_NAME: "alfresco-content-services"
+  MAX_REPO_REPLICAS:
+    sh: yq '.spec.maxReplicas' ./kustomize/{{.ENV}}/hpa-repository.yaml
+  MIN_REPO_REPLICAS:
+    sh: yq '.spec.minReplicas' ./kustomize/{{.ENV}}/hpa-repository.yaml
+  MAX_TIKA_REPLICAS:
+    sh: yq '.spec.maxReplicas' ./kustomize/{{.ENV}}/hpa-tika.yaml
+  MIN_TIKA_REPLICAS:
+    sh: yq '.spec.minReplicas' ./kustomize/{{.ENV}}/hpa-tika.yaml
+
 
 tasks:
   # Perform a helm upgrade on the alfresco-content-services chart
@@ -103,7 +113,8 @@ tasks:
     dir: ./kustomize/{{.ENV}}
     cmds:
       - |
-        helm upgrade --install alfresco-content-services alfresco/alfresco-content-services --version {{.CHART_VERSION}} --namespace {{.NAMESPACE}} \
+        RELEASE_NAME="{{.RELEASE_NAME}}"
+        helm upgrade --install $RELEASE_NAME alfresco/$RELEASE_NAME --version {{.CHART_VERSION}} --namespace {{.NAMESPACE}} \
         --values=../base/values.yaml --values=../base/values-versions.yaml --values=values.yaml \
         --set s3connector.config.bucketName={{.BUCKET_NAME}} \
         --set database.url={{.RDS_JDBC_URL}} \
@@ -115,9 +126,9 @@ tasks:
         {{.DEBUG_FLAG}} {{.ATOMIC_FLAG}} {{.DRY_RUN_FLAG}}
         echo " "
         echo "***** Helm upgrade completed *****"
-        echo "Helm revision: $(helm list -n {{.NAMESPACE}} | grep alfresco-content-services | awk '{print $10}')"
-        echo "Chart version: $(helm list -n {{.NAMESPACE}} | grep alfresco-content-services | awk '{print $9}')"
-        echo "ACS Version: $(helm list -n {{.NAMESPACE}} | grep alfresco-content-services | awk '{print $10}')"
+        echo "Helm revision: $(helm list -n {{.NAMESPACE}} | grep $RELEASE_NAME | awk '{print $10}')"
+        echo "Chart version: $(helm list -n {{.NAMESPACE}} | grep $RELEASE_NAME | awk '{print $9}')"
+        echo "ACS Version: $(helm list -n {{.NAMESPACE}} | grep $RELEASE_NAME | awk '{print $10}')"
         echo " "
 
   reset_allowlist:
@@ -130,16 +141,115 @@ tasks:
   # reindexes by id from the FROM_ID to the TO_ID
   # ID FORMAT: alf-node id
   reindex_by_id:
+    desc: >
+      Reindex Alfresco documents and/or metadata by ID range using Helm.
+      Requires FROM and TO environment variables to define the ID range.
+
+      Automatically scales up deployments if the ID range is greater than 100,000.
+
+      Optionally set INDEX_CONTENT to 'false' to skip content indexing and only reindex metadata.
+      Defaults to 'true'.
+
+      Example usage:
+        FROM=100000 TO=200000 task reindex_by_id
+        FROM=100000 TO=200000 INDEX_CONTENT=false task reindex_by_id
     cmds:
       - |
-        helm install "reindex-default-$(openssl rand -hex 4)" ./jobs/reindex --set "global.elasticsearch.host={{.OPENSEARCH_HOST}}" --set "fromId={{.FROM}}" --set "toId={{.TO}}" --namespace {{.NAMESPACE}}
+        if [ -z "{{.FROM}}" ]; then
+        echo "ERROR: FROM variable is not set" >&2
+          exit 1
+        fi
+        if [ -z "{{.TO}}" ]; then
+          echo "ERROR: TO variable is not set" >&2
+          exit 1
+        fi
+
+        INDEX_CONTENT="{{.INDEX_CONTENT}}"
+        if [ -z "$INDEX_CONTENT" ]; then
+          INDEX_CONTENT="true"
+        fi
+
+        RANGE=$((TO - FROM))
+        echo "📊 ID Range: $FROM to $TO (count: $RANGE)"
+
+        if [ "$RANGE" -gt 100000 ]; then
+          echo "🚀 Large ID range detected. Scaling up repository and tika deployments..."
+          task scale_up_deployments ENV={{.ENV}}
+        else
+          echo "ℹ️ Small ID range detected. No scaling needed."
+        fi
+
+        task cleanup_unused_reindex_configmaps ENV={{.ENV}}
+
+        helm install "reindex-default-$(openssl rand -hex 4)" ./jobs/reindex --set "global.elasticsearch.host={{.OPENSEARCH_HOST}}" --set "fromId={{.FROM}}" --set "toId={{.TO}}" --set "content=${INDEX_CONTENT}" --namespace {{.NAMESPACE}}
 
   # reindexes by date from the FROM_DATE to the TO_DATE
   # DATE FORMAT: YYYYMMDDHHMM
+  # To only reindex metadata, set INDEX_CONTENT to false e.g.
+  # INDEX_CONTENT=false task reindex_by_date
   reindex_by_date:
+    desc: >
+      Reindex Alfresco documents and/or metadata by date range using Helm.
+      Requires FROM and TO environment variables to define the range.
+
+      Optionally set INDEX_CONTENT to 'false' to skip content indexing and only reindex metadata.
+      Defaults to 'true' (index both content and metadata).
+
+      Example usage:
+        FROM=201706072250 TO=201706072350 task reindex_by_date
+        FROM=201706072250 TO=201706072350 INDEX_CONTENT=false task reindex_by_date    
     cmds:
       - |
-        helm install "reindex-default-$(openssl rand -hex 4)" ./jobs/reindex_date --set "global.elasticsearch.host={{.OPENSEARCH_HOST}}" --set "fromTime={{.FROM}}" --set "toTime={{.TO}}" --namespace {{.NAMESPACE}}
+        if [ -z "{{.FROM}}" ]; then
+          echo "ERROR: FROM variable is not set" >&2
+          exit 1
+        fi
+        if [ -z "{{.TO}}" ]; then
+          echo "ERROR: TO variable is not set" >&2
+          exit 1
+        fi
+
+        INDEX_CONTENT="{{.INDEX_CONTENT}}"
+        if [ -z "$INDEX_CONTENT" ]; then
+          INDEX_CONTENT="true"
+        fi
+
+        FROM="{{.FROM}}"
+        TO="{{.TO}}"
+        NS="{{.NAMESPACE}}"
+
+        CM="reindexing-${FROM}-${TO}-configmap"
+        PREFIX_CM="reindexing-${FROM}-${TO}-prefixes-configmap"
+
+        echo "🔍 Looking for active pods starting with reindexing-* in namespace $NS..."
+        REINDEX_PODS=$(kubectl get pods -n "$NS" --no-headers | awk '/^reindexing-/ && $3 != "Completed" && $3 != "Failed" { print $1 }')
+
+        CM_IN_USE=false
+        for POD in $(echo "$ACTIVE_PODS" | jq -r '.items[].metadata.name'); do
+          POD_JSON=$(kubectl get pod "$POD" -n "$NS" -o json)
+
+          if echo "$POD_JSON" | jq -e --arg CM "$CM" '.spec.volumes[]?.configMap.name == $CM' >/dev/null ||
+            echo "$POD_JSON" | jq -e --arg CM "$CM" '.spec.containers[].envFrom[]?.configMapRef.name == $CM' >/dev/null ||
+            echo "$POD_JSON" | jq -e --arg CM "$PREFIX_CM" '.spec.volumes[]?.configMap.name == $CM' >/dev/null ||
+            echo "$POD_JSON" | jq -e --arg CM "$PREFIX_CM" '.spec.containers[].envFrom[]?.configMapRef.name == $CM' >/dev/null; then
+            echo "⚠️  ConfigMap $CM or $PREFIX_CM is in use by pod $POD. Skipping deletion."
+            CM_IN_USE=true
+          fi
+        done
+
+        if [ "$CM_IN_USE" = false ]; then
+          echo "✅ No active pods are using the ConfigMaps. Safe to delete."
+          kubectl delete configmap "$CM" -n "$NS" --ignore-not-found
+          kubectl delete configmap "$PREFIX_CM" -n "$NS" --ignore-not-found
+        else
+          echo "⚠️  Skipping ConfigMap deletion to avoid disrupting running pods."
+        fi
+
+        echo "Scaling up deployments before reindexing..."
+        task reindex_scale_up ENV={{.ENV}}
+
+        echo "Running Helm install to run job..."
+        helm install "reindex-default-$(openssl rand -hex 4)" ./jobs/reindex_date --set "global.elasticsearch.host={{.OPENSEARCH_HOST}}" --set "fromTime=${FROM}" --set "toTime=${TO}" --set "content=${INDEX_CONTENT}" --namespace ${NS}
 
   helm_uninstall_prefix:
     vars:
@@ -162,3 +272,206 @@ tasks:
           echo "Deleting pod: $pod"
           kubectl delete pod "$pod" -n {{.NAMESPACE}} {{.FORCE_FLAG}}
         done
+
+  cleanup_unused_reindex_configmaps:
+    desc: "Delete all unused reindexing-* configmaps in a given namespace"
+    cmds:
+      - |
+        NS="{{.NAMESPACE}}"
+
+        echo "🔍 Finding all reindexing ConfigMaps in namespace $NS..."
+        CONFIGMAPS=$(kubectl get configmaps -n "$NS" -o json | jq -r '.items[].metadata.name' | grep '^reindexing-')
+
+        if [ -z "$CONFIGMAPS" ]; then
+          echo "✅ No reindexing ConfigMaps found."
+          exit 0
+        fi
+
+        # Get all active pods (not Completed/Failed)
+        ACTIVE_PODS=$(kubectl get pods -n "$NS" --field-selector=status.phase!=Succeeded,status.phase!=Failed -o json)
+
+        for CM in $CONFIGMAPS; do
+          echo "🔎 Checking if ConfigMap $CM is in use..."
+
+          CM_IN_USE=false
+          for POD in $(echo "$ACTIVE_PODS" | jq -r '.items[].metadata.name'); do
+            POD_JSON=$(kubectl get pod "$POD" -n "$NS" -o json)
+
+            if echo "$POD_JSON" | jq -e --arg CM "$CM" '.spec.volumes[]?.configMap.name == $CM' >/dev/null ||
+              echo "$POD_JSON" | jq -e --arg CM "$CM" '.spec.containers[].envFrom[]?.configMapRef.name == $CM' >/dev/null; then
+              echo "⚠️  In use by pod $POD"
+              CM_IN_USE=true
+              break
+            fi
+          done
+
+          if [ "$CM_IN_USE" = false ]; then
+            echo "🗑️  Deleting unused ConfigMap $CM"
+            kubectl delete configmap "$CM" -n "$NS"
+          else
+            echo "⏭️  Skipping $CM as it's in use"
+          fi
+        done
+
+  restart_deployments:
+    desc: "Restart all ACS deployments in the specified namespace"
+    cmds:
+      - |
+        NS="{{.NAMESPACE}}"
+        RELEASE_NAME="{{.RELEASE_NAME}}"
+        echo "Restarting deployments in namespace $NS"
+        # Get all deployment names, then filter only the ones that start with the release name
+        DEPLOYMENTS=$(kubectl get deployments -n "$NS" -o jsonpath='{.items[*].metadata.name}' | tr ' ' '\n' | grep "^${RELEASE_NAME}-")
+        if [ -z "$DEPLOYMENTS" ]; then
+          echo "No deployments found in namespace $NS"
+          exit 0
+        fi
+
+        for DEPLOYMENT in $DEPLOYMENTS; do
+          echo "Restarting deployment: $DEPLOYMENT"
+          kubectl rollout restart deployment "$DEPLOYMENT" -n "$NS"
+        done
+
+  reindex_scale_up:
+    desc: "Scale up ACS deployments to their maxReplicas when reindexing by setting HPA minReplicas to match maxReplicas"
+    cmds:
+      - |
+        NS="{{.NAMESPACE}}"
+        RELEASE_NAME="{{.RELEASE_NAME}}"
+        MAX_REPO_REPLICAS="{{.MAX_REPO_REPLICAS}}"
+        MIN_REPO_REPLICAS="{{.MIN_REPO_REPLICAS}}"
+        MAX_TIKA_REPLICAS="{{.MAX_TIKA_REPLICAS}}"
+        MIN_TIKA_REPLICAS="{{.MIN_TIKA_REPLICAS}}"
+
+        echo "Updating HPA minReplicas to match maxReplicas for Repository"
+        kubectl patch hpa $RELEASE_NAME-hpa-repository -n "$NS" \
+          --type='merge' \
+          -p "{\"spec\": {\"minReplicas\": ${MAX_REPO_REPLICAS}}}"
+
+        echo "Updating HPA minReplicas to match maxReplicas for Tika"
+        kubectl patch hpa $RELEASE_NAME-hpa-tika -n "$NS" \
+          --type='merge' \
+          -p "{\"spec\": {\"minReplicas\": ${MAX_TIKA_REPLICAS}}}"
+
+  reindex_scale_down:
+    desc: "Scale down ACS deployments to their default minReplicas after reindexing by resetting HPA minReplicas"
+    cmds:
+      - |
+        NS="{{.NAMESPACE}}"
+        RELEASE_NAME="{{.RELEASE_NAME}}"
+        MAX_REPO_REPLICAS="{{.MAX_REPO_REPLICAS}}"
+        MIN_REPO_REPLICAS="{{.MIN_REPO_REPLICAS}}"
+        MAX_TIKA_REPLICAS="{{.MAX_TIKA_REPLICAS}}"
+        MIN_TIKA_REPLICAS="{{.MIN_TIKA_REPLICAS}}"
+
+        echo "Updating HPA minReplicas to match maxReplicas for Repository"
+        kubectl patch hpa $RELEASE_NAME-hpa-repository -n "$NS" \
+          --type='merge' \
+          -p "{\"spec\": {\"minReplicas\": ${MIN_REPO_REPLICAS}}}"
+
+        echo "Updating HPA minReplicas to match maxReplicas for Tika"
+        kubectl patch hpa $RELEASE_NAME-hpa-tika -n "$NS" \
+          --type='merge' \
+          -p "{\"spec\": {\"minReplicas\": ${MIN_TIKA_REPLICAS}}}"
+
+  scale_up_deployments:
+    desc: "Scale up all ACS deployments based on config file defaults"
+    dir: ./kustomize/{{.ENV}}
+    cmds:
+      - |
+        NS="{{.NAMESPACE}}"
+        RELEASE_NAME="{{.RELEASE_NAME}}"
+
+        # HPA configured deployments
+        MAX_REPO_REPLICAS="{{.MAX_REPO_REPLICAS}}"
+        MIN_REPO_REPLICAS="{{.MIN_REPO_REPLICAS}}"
+        MAX_TIKA_REPLICAS="{{.MAX_TIKA_REPLICAS}}"
+        MIN_TIKA_REPLICAS="{{.MIN_TIKA_REPLICAS}}"
+
+        echo "Reset HPA Replicas for Repository"
+        kubectl patch hpa $RELEASE_NAME-hpa-repository -n "$NS" \
+          --type='merge' \
+          -p "{\"spec\": {\"minReplicas\": ${MIN_REPO_REPLICAS}}}"
+        kubectl patch hpa $RELEASE_NAME-hpa-repository -n "$NS" \
+          --type='merge' \
+          -p "{\"spec\": {\"maxReplicas\": ${MAX_REPO_REPLICAS}}}"
+
+        echo "Reset HPA Replicas for Tika"
+        kubectl patch hpa $RELEASE_NAME-hpa-tika -n "$NS" \
+          --type='merge' \
+          -p "{\"spec\": {\"minReplicas\": ${MIN_TIKA_REPLICAS}}}"
+        kubectl patch hpa $RELEASE_NAME-hpa-tika -n "$NS" \
+          --type='merge' \
+          -p "{\"spec\": {\"maxReplicas\": ${MAX_TIKA_REPLICAS}}}"
+
+        kubectl scale deployment $RELEASE_NAME-alfresco-repository --replicas=$MIN_REPO_REPLICAS
+        kubectl scale deployment $RELEASE_NAME-tika --replicas=$MIN_TIKA_REPLICAS
+
+        # non-HPA configured deployments
+        # Load default replica counts from values.yaml or base values.yaml
+        TRANSFORM_ROUTER_REPLICAS=$(yq '(.["alfresco-transform-service"].transformrouter.replicaCount) // (load("../base/values.yaml") | .["alfresco-transform-service"].transformrouter.replicaCount) // 2' values.yaml)
+
+        # The below deployments use the same transformrouter default replica count if not specified
+        BASE_TRANSFORM_ROUTER_REPLICAS=$(yq '(["alfresco-transform-service"].transformrouter.replicaCount) // 2' ../base/values.yaml)
+
+        TRANSFORM_MISC_REPLICAS=$(yq '.["alfresco-transform-service"].transformmisc.replicaCount // ""' values.yaml); [ -z "$TRANSFORM_MISC_REPLICAS" ] && TRANSFORM_MISC_REPLICAS=$(yq '.["alfresco-transform-service"].transformmisc.replicaCount // ""' ../base/values.yaml); [ -z "$TRANSFORM_MISC_REPLICAS" ] && TRANSFORM_MISC_REPLICAS=$BASE_TRANSFORM_ROUTER_REPLICAS
+
+        IMAGEMAGICK_REPLICAS=$(yq '.["alfresco-transform-service"].imagemagick.replicaCount // ""' values.yaml); [ -z "$IMAGEMAGICK_REPLICAS" ] && IMAGEMAGICK_REPLICAS=$(yq '.["alfresco-transform-service"].imagemagick.replicaCount // ""' ../base/values.yaml); [ -z "$IMAGEMAGICK_REPLICAS" ] && IMAGEMAGICK_REPLICAS=$BASE_TRANSFORM_ROUTER_REPLICAS
+
+        LIBREOFFICE_REPLICAS=$(yq '.["alfresco-transform-service"].libreoffice.replicaCount // ""' values.yaml); [ -z "$LIBREOFFICE_REPLICAS" ] && LIBREOFFICE_REPLICAS=$(yq '.["alfresco-transform-service"].libreoffice.replicaCount // ""' ../base/values.yaml); [ -z "$LIBREOFFICE_REPLICAS" ] && LIBREOFFICE_REPLICAS=$BASE_TRANSFORM_ROUTER_REPLICAS
+
+        PDFRENDERER_REPLICAS=$(yq '.["alfresco-transform-service"].pdfrenderer.replicaCount // ""' values.yaml); [ -z "$PDFRENDERER_REPLICAS" ] && PDFRENDERER_REPLICAS=$(yq '.["alfresco-transform-service"].pdfrenderer.replicaCount // ""' ../base/values.yaml); [ -z "$PDFRENDERER_REPLICAS" ] && PDFRENDERER_REPLICAS=$BASE_TRANSFORM_ROUTER_REPLICAS
+
+        PATH_REPLICAS=$(yq '(.["alfresco-transform-service"].path.replicaCount) // (load("../base/values.yaml") | .["alfresco-search-enterprise"].liveIndexing.path.replicaCount) // 1' values.yaml)
+        CONTENT_REPLICAS=$(yq '(.["alfresco-search-enterprise"].liveIndexing.content.replicaCount) // (load("../base/values.yaml") | .["alfresco-search-enterprise"].liveIndexing.content.replicaCount) // 1' values.yaml)
+        METADATA_REPLICAS=$(yq '(.["alfresco-search-enterprise"].liveIndexing.metadata.replicaCount) // (load("../base/values.yaml") | .["alfresco-search-enterprise"].liveIndexing.metadata.replicaCount) // 1' values.yaml)
+        MEDIATION_REPLICAS=$(yq '(.["alfresco-search-enterprise"].liveIndexing.mediation.replicaCount) // (load("../base/values.yaml") | .["alfresco-search-enterprise"].liveIndexing.mediation.replicaCount) // 1' values.yaml)
+
+        SHARE_REPLICAS=$(yq '(.share.replicaCount) // (load("../base/values.yaml") | .share.replicaCount) // 1' values.yaml)
+
+        kubectl scale deployment $RELEASE_NAME-share --replicas=$SHARE_REPLICAS
+        kubectl scale deployment $RELEASE_NAME-imagemagick --replicas=$IMAGEMAGICK_REPLICAS
+        kubectl scale deployment $RELEASE_NAME-libreoffice --replicas=$LIBREOFFICE_REPLICAS
+        kubectl scale deployment $RELEASE_NAME-pdfrenderer --replicas=$PDFRENDERER_REPLICAS
+        kubectl scale deployment $RELEASE_NAME-transform-misc --replicas=$TRANSFORM_MISC_REPLICAS
+        kubectl scale deployment $RELEASE_NAME-transform-router --replicas=$TRANSFORM_ROUTER_REPLICAS
+        kubectl scale deployment $RELEASE_NAME-alfresco-search-enterprise-content --replicas=$CONTENT_REPLICAS
+        kubectl scale deployment $RELEASE_NAME-alfresco-search-enterprise-mediation --replicas=$MEDIATION_REPLICAS
+        kubectl scale deployment $RELEASE_NAME-alfresco-search-enterprise-metadata --replicas=$METADATA_REPLICAS
+        kubectl scale deployment $RELEASE_NAME-alfresco-search-enterprise-path --replicas=$PATH_REPLICAS
+
+
+  scale_down_deployments:
+    desc: "Scale down all ACS deployments to 0 replicas"
+    cmds:
+      - |
+        NS="{{.NAMESPACE}}"
+        RELEASE_NAME="{{.RELEASE_NAME}}"
+
+        echo "Scaling down deployments in namespace $NS"
+
+        # HPA configured deployments
+
+        echo "Updating HPA Replicas for Repository"
+        kubectl patch hpa $RELEASE_NAME-hpa-repository -n "$NS" \
+          --type='merge' \
+          -p "{\"spec\": {\"minReplicas\": 0}}"
+        kubectl patch hpa $RELEASE_NAME-hpa-repository -n "$NS" \
+          --type='merge' \
+          -p "{\"spec\": {\"maxReplicas\": 0}}"
+
+        echo "Updating HPA Replicas for Tika"
+        kubectl patch hpa $RELEASE_NAME-hpa-tika -n "$NS" \
+          --type='merge' \
+          -p "{\"spec\": {\"minReplicas\": 0}}"
+        kubectl patch hpa $RELEASE_NAME-hpa-tika -n "$NS" \
+          --type='merge' \
+          -p "{\"spec\": {\"maxReplicas\": 0}}"
+
+        DEPLOYMENTS=$(kubectl get deployments -n "$NS" -o jsonpath='{.items[*].metadata.name}' | tr ' ' '\n' | grep "^${RELEASE_NAME}-")
+        for deployment in $DEPLOYMENTS; do
+            echo "Scaling down deployment: $deployment"
+            kubectl scale $deployment --replicas=0
+        done
+
+        
