chore: Update helm chart to 7.0.3 (#113)
* chore: update readme v1

* new helm chart version updates

* Update Taskfile.yml

* values changes

* patching

* patching for filestore url

* Update readme (#117)

* fix: matrix env typo (#110)

* chore: add awscli to utils container (#111)

* correct values for preprod

* move to config map as source of truth

* create config map with correct values in it and update size limit

---------

Co-authored-by: Andrew Moore <20435317+andrewmooreio@users.noreply.github.com>

* Update migrate-s3.yaml

* Update migrate-s3.yaml

* Update migrate-s3.yaml

* Update migrate-s3.yaml

* Update migrate-s3.yaml

* add labels

* chore: tidy the task file

* chore: add dev

* update all envs for new chart

* attempt poc

---------

Co-authored-by: Andrew Moore <20435317+andrewmooreio@users.noreply.github.com>

diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -2,14 +2,30 @@ version: "3"
 
 vars:
   ENV: "{{.ENV}}"
+  FROM: "{{.FROM}}"
+  TO: "{{.TO}}"
+  FORCE: "{{.FORCE}}"
   NAMESPACE:
-    sh: if [ "{{.ENV}}" = "poc" ]; then echo "hmpps-delius-alfrsco-{{.ENV}}"; else echo "hmpps-delius-alfresco-{{.ENV}}"; fi
+    sh: |
+      if [ -z "{{.ENV}}" ]; then
+        echo "ERROR: ENV variable is not set" >&2
+        exit 1
+      elif [ "{{.ENV}}" = "poc" ]; then
+        echo "hmpps-delius-alfrsco-{{.ENV}}"
+      else
+        echo "hmpps-delius-alfresco-{{.ENV}}"
+      fi
   BUCKET_NAME:
     sh: kubectl get secret s3-bucket-output -n {{.NAMESPACE}} -o jsonpath='{.data.BUCKET_NAME}' | base64 --decode
   OPEN_SEARCH_PREFIX:
     sh: kubectl get svc --namespace {{.NAMESPACE}} | grep 'opensearch-proxy-service-cloud-platform' | awk '{ print $1 }'
   OPENSEARCH_HOST:
     sh: echo "{{.OPEN_SEARCH_PREFIX}}.{{.NAMESPACE}}.svc.cluster.local"
+  MESSAGEBROKER_URL:
+    sh: |
+      kubectl get secrets amazon-mq-broker-secret -o json | \
+      jq -r ".data | map_values(@base64d) | .BROKER_URL" | \
+      sed -e 's/(/\\(/g' -e 's/)/\\)/g' -e 's/,/\\,/g'
   ALLOWLIST:
     sh: yq 'join(",")' ./kustomize/{{.ENV}}/allowlist.yaml
   RDS_JDBC_URL:
@@ -22,9 +38,10 @@ vars:
   ATOMIC: "true"
   ATOMIC_FLAG:
     sh: if [ "{{.ATOMIC}}" = "true" ]; then echo "--atomic"; else echo ""; fi
-  CHART_VERSION: "6.0.2"
+  CHART_VERSION: "7.0.3"
 
 tasks:
+  # Perform a helm upgrade on the alfresco-content-services chart
   helm_upgrade:
     cmds:
       - echo "NAMESPACE set to {{.NAMESPACE}}"
@@ -82,11 +99,12 @@ tasks:
     cmds:
       - |
         helm upgrade --install alfresco-content-services alfresco/alfresco-content-services --version {{.CHART_VERSION}} --namespace {{.NAMESPACE}} \
-        --values=../base/values.yaml --values=values.yaml \
+        --values=../base/values.yaml --values=../base/values-versions.yaml --values=values.yaml \
         --set s3connector.config.bucketName={{.BUCKET_NAME}} \
         --set database.url={{.RDS_JDBC_URL}} \
-        --set global.elasticsearch.host={{.OPENSEARCH_HOST}} \
-        --set alfresco-search-enterprise.searchIndex.host={{.OPENSEARCH_HOST}} \
+        --set-string messageBroker.url="{{.MESSAGEBROKER_URL}}" \
+        --set global.search.url=http://{{.OPENSEARCH_HOST}}:8080 \
+        --set global.search.host={{.OPENSEARCH_HOST}} \
         --wait --timeout=60m \
         --post-renderer ../kustomizer.sh --post-renderer-args "{{.HELM_POST_RENDERER_ARGS}}" \
         {{.DEBUG_FLAG}} {{.ATOMIC_FLAG}}
@@ -103,225 +121,28 @@ tasks:
     cmds:
       - yq '.metadata.annotations."nginx.ingress.kubernetes.io/whitelist-source-range" = "placeholder"' -i patch-ingress-repository.yaml
       - yq '.metadata.annotations."nginx.ingress.kubernetes.io/whitelist-source-range" = "placeholder"' -i patch-ingress-share.yaml
-  
-  simple_reindex:
-    cmds:
-      - | 
-        helm install "reindex-default-$(openssl rand -hex 4)" ./jobs/reindex --set "global.elasticsearch.host={{.OPENSEARCH_HOST}}" --set "fromId=27451380" --set "toId=27908429" --namespace {{.NAMESPACE}}  
 
-  reindex_list:
-    cmds:
-      - | 
-        # Set your batch size (you can adjust this number as needed)
-        BATCH_SIZE=40
-
-        # Path to your JSON file containing the list of IDs
-        JSON_FILE="ids.json"
-
-        RANDOM_ID=$(openssl rand -hex 4)
-
-        # Function to create Helm job for a given batch of IDs
-        create_helm_job() {
-            # Concatenate the batch of IDs into a comma-separated string
-            # $1, $2, ... represent individual IDs
-            local idList=""
-            for id in "$@"; do
-                if [ -z "$idList" ]; then
-                    idList="$id"
-                else
-                    idList="$idList,$id"
-                fi
-            done
-
-            # Debugging: print the batch being passed
-            echo "Creating job for IDs: $idList"  # This will show only the batch, not the whole list
-
-            # Run Helm command to create the job with the current batch of IDs
-            helm upgrade --install "reindex-list-${RANDOM_ID}" \
-                --set "idList={${idList}}" \
-                --set "global.elasticsearch.host={{.OPENSEARCH_HOST}}" \
-                --set "global.namespace={{.NAMESPACE}}" \
-                ./jobs/reindex-list \
-                --namespace "{{.NAMESPACE}}"
-            echo "Waiting for the jobs to complete..."
-            kubectl wait --for=condition=complete job --namespace {{.NAMESPACE}} -l "reindex-type=list" --timeout=10h || echo "Jobs completed!"
-            echo "Jobs completed!"
-        }
-
-        # Parse the list of IDs from the JSON file using jq
-        # The IDs will be saved as a space-separated list into the 'ids' variable
-        ids=$(jq -r '.list[]' "$JSON_FILE")
-
-        # Initialize the index for processing
-        index=0
-
-        # Loop over the IDs and create jobs in batches
-        for id in $ids; do
-            # Add the current ID to the current batch
-            batch[$index]="$id"
-            index=$((index + 1))
-
-            # If the batch reaches the specified batch size, process it
-            if [ "$index" -ge "$BATCH_SIZE" ]; then
-                # Create the Helm job for the current batch
-                create_helm_job "${batch[@]}"
-
-                # Reset the batch for the next set of IDs
-                index=0
-                unset batch
-                # kubectl wait --for=condition=complete job --namespace {{.NAMESPACE}} -l "reindex-type=list" --timeout=10h || echo "Jobs completed!"
-                helm uninstall "reindex-list-${RANDOM_ID}" --namespace {{.NAMESPACE}}
-            fi
-        done
-
-        # If there are any remaining IDs (less than BATCH_SIZE), create the last job
-        if [ "$index" -gt 0 ]; then
-            create_helm_job "${batch[@]}"
-        fi
-        
-        echo "All jobs have been created!"
-        echo "Cleaning up..."
-        helm uninstall "reindex-list-${RANDOM_ID}" --namespace {{.NAMESPACE}}
-        echo "Cleanup complete!"
-
-
-
-
-  simple_reindex_date:
-    cmds:
-      - | 
-        helm install "reindex-default-$(openssl rand -hex 4)" ./jobs/reindex_date --set "global.elasticsearch.host={{.OPENSEARCH_HOST}}" --set "fromTime=201707060001" --set "toTime=201707070001" --namespace {{.NAMESPACE}}
-
-  simple_reindex_date_metadata-only:
-    cmds:
-      - | 
-        helm install "reindex-default-date-meta" ./jobs/reindex_date --set "global.elasticsearch.host={{.OPENSEARCH_HOST}}" --set "fromTime=202402010100" --set "toTime=202402100100" --set "content=false" --namespace {{.NAMESPACE}}
-
-  batch_reindex:
-    vars:
-      START: "{{.START | default 0}}"
-      END: "{{.END | default 10050}}"
-      CHUNK: "{{.CHUNK | default 1000}}"
-      CONCURRENCY: "{{.CONCURRENCY | default 5}}"
-      ARRAY:
-        sh: |
-          arr=$(
-            for i in $(seq -f "%.0f" {{.START}} {{.CHUNK}} {{.END}}); do
-              new_start=$i
-              end=$((i + {{.CHUNK}} - 1))
-              if [ $end -gt {{.END}} ]; then
-                end={{.END}}
-              fi
-          cat << EOF
-          ${new_start}-${end}
-          EOF
-            done
-          )
-          echo "$arr"
-    cmds:
-      - echo "Starting batch reindex from {{.START}} to {{.END}} in chunks of {{.CHUNK}}"
-      - task: run_reindex_batches
-        vars:
-          OPENSEARCH_HOST: "{{.OPENSEARCH_HOST}}"
-          NAMESPACE: "{{.NAMESPACE}}"
-          ARRAY: "{{.ARRAY}}"
-          CONCURRENCY: "{{.CONCURRENCY}}"
-      - task: reindex_helm_cleanup
-        vars:
-          NAMESPACE: "{{.NAMESPACE}}"
-
-  run_reindex_batches:
+  # reindexes by id from the FROM_ID to the TO_ID
+  # ID FORMAT: alf-node id
+  reindex_by_id:
     cmds:
       - |
-        pending="{{.ARRAY}}"
-        # count the number of items
-        total_items=$(echo "$pending" | wc -l)
-        echo "Total items: $total_items"
+        helm install "reindex-default-$(openssl rand -hex 4)" ./jobs/reindex --set "global.elasticsearch.host={{.OPENSEARCH_HOST}}" --set "fromId={{.FROM}}" --set "toId={{.TO}}" --namespace {{.NAMESPACE}}
 
-        previous_completed=$(cat completed.txt) || true
-        if [ -z "$previous_completed" ]; then
-          echo "No previous completed items"
-        else
-          echo "Count of previous completed items: $(echo "$previous_completed" | wc -l)"
-        fi
-
-        # remove the completed items from the pending list
-        for item in $previous_completed; do
-          pending=$(echo "$pending" | grep -v "$item")
-        done
-        
-        total_items=$(echo "$pending" | wc -l)
-        echo "Total items: $total_items"
-
-
-        started=()
-        completed=()
-
-        # while pending is not empty
-        while [ -n "$pending" ]; do
-            # echo "Pending: $pending"
-            # Get the first item
-            item=$(echo "$pending" | head -n 1)
-            echo "Processing item: $item"
-
-            # Get the start and end values
-            start=$(echo "$item" | cut -d '-' -f 1)
-            end=$(echo "$item" | cut -d '-' -f 2)
-            echo "Start: $start, End: $end"
-
-            # check the number of jobs running
-            running_jobs=$(kubectl get jobs --namespace {{.NAMESPACE}} -l "reindex-job" -o json | jq '.items | length')
-            echo "Running jobs: $running_jobs"
-            if [ $running_jobs -ge {{.CONCURRENCY}} ]; then
-                echo "No available slots, waiting for 5 seconds"
-                sleep 5
-            else 
-              echo "Found at least 1 available slot!"
-              echo "Available slots left: $(({{.CONCURRENCY}} - $running_jobs))"
-              # run the job
-              echo "helm install reindex-${start}-${end} ./jobs/reindex --set global.elasticsearch.host={{.OPENSEARCH_HOST}} --set fromId=${start} --set toId=${end} --namespace {{.NAMESPACE}}"  
-              helm install "reindex-${start}-${end}" ./jobs/reindex --set "global.elasticsearch.host={{.OPENSEARCH_HOST}}" --set "fromId=${start}" --set "toId=${end}" --namespace {{.NAMESPACE}}
-              # Remove the item from the list
-              pending=$(echo "$pending" | tail -n +2)
-            fi
-
-            # check for completed jobs
-            completed_jobs=$(kubectl get jobs --namespace {{.NAMESPACE}} -l "reindex-job" -o json | jq -r '.items[] | select(.status.succeeded == 1) | .metadata.labels["reindex-job"]')
-            if [ -z "$completed_jobs" ]; then
-              echo "No completed jobs"
-            else
-              echo "Completed jobs: $completed_jobs"
-              echo "$completed_jobs" | while IFS= read -r job; do
-                echo "Processing completed job: $job"
-                completed+=("$job")
-                echo "$job" >> completed.txt
-                echo "Job $job completed"
-                helm uninstall "reindex-$job" --namespace {{.NAMESPACE}}
-              done
-            fi
-        done
-
-  reindex_helm_cleanup:
+  # reindexes by date from the FROM_DATE to the TO_DATE
+  # DATE FORMAT: YYYYMMDDHHMM
+  reindex_by_date:
     cmds:
       - |
-        # wait for all jobs to complete
-        kubectl wait --for=condition=complete jobs --namespace {{.NAMESPACE}} -l "reindex-job" --timeout=4h
+        helm install "reindex-default-$(openssl rand -hex 4)" ./jobs/reindex_date --set "global.elasticsearch.host={{.OPENSEARCH_HOST}}" --set "fromTime={{.FROM}}" --set "toTime={{.TO}}" --namespace {{.NAMESPACE}}
 
-        completed_jobs=$(kubectl get jobs --namespace {{.NAMESPACE}} -l "reindex-job" -o json | jq -r '.items[] | select(.status.succeeded == 1) | .metadata.labels["reindex-job"]')
-        if [ -z "$completed_jobs" ]; then
-          echo "No completed jobs"
-        else
-          echo "Completed jobs: $completed_jobs"
-          echo "$completed_jobs" | while IFS= read -r job; do
-            echo "Processing completed job: $job"
-            completed+=("$job")
-            echo "$job" >> completed.txt
-            echo "Job $job completed"
-            helm uninstall "reindex-$job" --namespace {{.NAMESPACE}}
-          done
-        fi
+  # reindex_by_date_metadata-only:
+  #   cmds:
+  #     - |
+  #       helm install "reindex-default-date-meta" ./jobs/reindex_date --set "global.elasticsearch.host={{.OPENSEARCH_HOST}}" --set "fromTime=202402010100" --set "toTime=202402100100" --set "content=false" --namespace {{.NAMESPACE}}
 
-  helm_bulk_uninstall:
+  # uninstalls all helm releases with the prefix
+  helm_uninstall_prefix:
     vars:
       PREFIX: "{{.PREFIX}}"
     cmds:
@@ -330,4 +151,15 @@ tasks:
           echo "Uninstalling release: $release"
           helm uninstall "$release" -n "$NAMESPACE"
         done
-        
+
+  kubectl_remove_pods_prefix:
+    vars:
+      PREFIX: "{{.PREFIX}}"
+      FORCE_FLAG:
+        sh: if [ "{{.FORCE}}" = "true" ]; then echo "--force"; else echo ""; fi
+    cmds:
+      - |
+        kubectl get pods -n {{.NAMESPACE}} | grep "^{{.PREFIX}}" | awk '{print $1}' | while IFS= read -r pod; do
+          echo "Deleting pod: $pod"
+          kubectl delete pod "$pod" -n "$NAMESPACE" {{.FORCE_FLAG}}
+        done
