:sparkles: Update DB Refresh workflow to include Slack notifications
* :sparkles: Update DB Refresh workflow to include Slack notifications

* 🐛 poc now uses opensearch

* Update data-refresh.yaml

* --ignore-not-found for helm uninstall

* Happy Helming

* Update data-refresh.yaml

* 🐛 Correct service account names for refresh jobs

* fix: Add curl package and fix Slack message

* typo

* :sparkles: create image and update job

Update job.yaml

Update job.yaml

Update job.yaml

Update job.yaml

Update job.yaml

Update job.yaml

Update job.yaml

Update job.yaml

Update Dockerfile

Update job.yaml

Update Dockerfile

Update Dockerfile

Update job.yaml

absolute dirs

Update job.yaml

Update job.yaml

Update job.yaml

Update job.yaml

Update Dockerfile

non root support

Update job.yaml

Update data-refresh.yaml

up

Update build-push-db-utils.yml

rename

Update build-push-db-utils.yml

Update build-push-db-utils.yml

no need to install jq

no password

update jobs for refresh

* Update job.yaml

* Update job.yaml

* Update job.yaml

* Update job.yaml

* Update job.yaml

* Update job.yaml

* Update job.yaml

* Update job.yaml

* t

* Update job.yaml

* Update job.yaml

* Update job.yaml

* Update job.yaml

* Update job.yaml

* typo

* Update job.yaml

* Update job.yaml

* Update data-refresh.yaml

---------

Co-Authored-By: George Taylor <george.taylor@digital.justice.gov.uk>

diff --git a/jobs/refresh-db/templates/job.yaml b/jobs/refresh-db/templates/job.yaml
--- a/jobs/refresh-db/templates/job.yaml
+++ b/jobs/refresh-db/templates/job.yaml
@@ -7,14 +7,37 @@ data:
   entrypoint.sh: |-
     #!/bin/bash
     set -e
+    trap 'send_slack_notification $?' EXIT
+    
+    function send_slack_notification() {
+      STATUS=$1
+      if [ "$STATUS" -eq 0 ]; then
+        JSON_PAYLOAD=$(jq -n --arg text "Refresh DB (${SRC_ENV} to ${DST_ENV}) job succeeded" '{text: $text}')
+      else
+        ERROR_MSG=$(tail -n 10 ~/error.log) || ERROR_MSG="Unknown error"
+        JSON_PAYLOAD=$(jq -n --arg text "Refresh DB (${SRC_ENV} to ${DST_ENV}) job failed with error: $ERROR_MSG" '{text: $text}')
+      fi
+      curl -X POST -H 'Content-type: application/json' --data "$JSON_PAYLOAD" $SLACK_WEBHOOK_URL
+    }
+
     echo "${SRC_DB_HOST}:5432:${SRC_DB_NAME}:${SRC_DB_USER}:${SRC_DB_PASS}" > ~/.pgpass
     echo "${DST_DB_HOST}:5432:${DST_DB_NAME}:${DST_DB_USER}:${DST_DB_PASS}" >> ~/.pgpass
+    cat ~/.pgpass
     chmod 0600 ~/.pgpass
+    chown job:job ~/.pgpass
     set -x
 
-    pg_dump --jobs=4 --host="$SRC_DB_HOST" --username="$SRC_DB_USER" --dbname="$SRC_DB_NAME" --no-owner --no-privileges --verbose --format=directory --file=/tmp/db-dump
-    pg_restore --jobs=4 --host="$DST_DB_HOST" --username="$DST_DB_USER" --dbname="$DST_DB_NAME" --clean --if-exists --no-owner --no-privileges --verbose /tmp/db-dump
-    rm -rv /tmp/db-dump ~/.pgpass
+    # Dump the source database
+    pg_dump --jobs=4 --host="$SRC_DB_HOST" --username="$SRC_DB_USER" --dbname="$SRC_DB_NAME" --no-owner --no-privileges --verbose --format=directory --file=/home/job/db-dump 2> >(tee ~/error.log >&2)
+
+    psql --host="$DST_DB_HOST" --username="$DST_DB_USER" --dbname="$DST_DB_NAME" -c "drop schema if exists public cascade;" 2> >(tee ~/error.log >&2)
+
+    psql --host="$DST_DB_HOST" --username="$DST_DB_USER" --dbname="$DST_DB_NAME" -c "create schema public;" 2> >(tee ~/error.log >&2)
+
+    # Restore the source database dump to the destination database
+    pg_restore --jobs=4 --host="$DST_DB_HOST" --username="$DST_DB_USER" --dbname="$DST_DB_NAME" --no-owner --no-privileges --verbose /home/job/db-dump 2> >(tee ~/error.log >&2)
+    rm -rv /home/job/db-dump ~/.pgpass
+
 ---
 apiVersion: batch/v1
 kind: Job
@@ -25,7 +48,7 @@ spec:
     spec:
       containers:
       - name: refresh-db
-        image: postgres:14
+        image: ghcr.io/ministryofjustice/hmpps-delius-alfresco-db-utils:NIT-1403-alfresco-move-away-from-long-running-github-workflows-10114657186
         imagePullPolicy: IfNotPresent
         resources:
           limits:
@@ -34,6 +57,8 @@ spec:
         command:
         - /bin/entrypoint.sh
         env:
+        - name: HOME
+          value: "/home/job"
         - name: SRC_DB_NAME
           valueFrom:
             secretKeyRef:
@@ -74,6 +99,12 @@ spec:
             secretKeyRef:
               name: rds-instance-output-{{ .Values.destinationEnvironment }}
               key: RDS_INSTANCE_ADDRESS
+        - name: SLACK_WEBHOOK_URL
+          value: "{{ .Values.slackWebhookUrl }}"
+        - name: SRC_ENV
+          value: "{{ .Values.sourceEnvironment }}"
+        - name: DST_ENV
+          value: "{{ .Values.destinationEnvironment }}"
         volumeMounts:
         - name: refresh-db-script
           mountPath: /bin/entrypoint.sh
@@ -90,8 +121,8 @@ spec:
               - ALL
           seccompProfile:
             type: RuntimeDefault
-      serviceAccount: hmpps-migration-development
-      serviceAccountName: hmpps-migration-development
+      serviceAccount: hmpps-migration-dev
+      serviceAccountName: hmpps-migration-dev
       restartPolicy: Never
       volumes:
       - name: refresh-db-script
