:sparkles: create image and update job
Update job.yaml

Update job.yaml

Update job.yaml

Update job.yaml

Update job.yaml

Update job.yaml

Update job.yaml

Update job.yaml

Update Dockerfile

Update job.yaml

Update Dockerfile

Update Dockerfile

Update job.yaml

absolute dirs

Update job.yaml

Update job.yaml

Update job.yaml

Update job.yaml

Update Dockerfile

non root support

Update job.yaml

Update data-refresh.yaml

up

Update build-push-db-utils.yml

rename

Update build-push-db-utils.yml

Update build-push-db-utils.yml

no need to install jq

no password

update jobs for refresh

diff --git a/jobs/refresh-db/templates/job.yaml b/jobs/refresh-db/templates/job.yaml
--- a/jobs/refresh-db/templates/job.yaml
+++ b/jobs/refresh-db/templates/job.yaml
@@ -7,31 +7,36 @@ data:
   entrypoint.sh: |-
     #!/bin/bash
     set -e
-    trap 'send_slack_notification $? "$ERROR_MSG"' EXIT
-
-    apt-get update && apt-get install -y curl
-
+    trap 'send_slack_notification $?' EXIT
+    
     function send_slack_notification() {
       STATUS=$1
-      MESSAGE=$2
       if [ "$STATUS" -eq 0 ]; then
-        TEXT="Refresh DB (${SRC_ENV} to ${DST_ENV}) job succeeded."
+        JSON_PAYLOAD=$(jq -n --arg text "Refresh DB (${SRC_ENV} to ${DST_ENV}) job succeeded" '{text: $text}')
       else
-        TEXT="Refresh DB (${SRC_ENV} to ${DST_ENV}) job failed with error: $MESSAGE"
+        ERROR_MSG=$(tail -n 10 ~/error.log) || ERROR_MSG="Unknown error"
+        JSON_PAYLOAD=$(jq -n --arg text "Refresh DB (${SRC_ENV} to ${DST_ENV}) job failed with error: $ERROR_MSG" '{text: $text}')
       fi
-      curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"${TEXT}\"}" $SLACK_WEBHOOK_URL
+      curl -X POST -H 'Content-type: application/json' --data "$JSON_PAYLOAD" $SLACK_WEBHOOK_URL
     }
 
-    {
-      echo "${SRC_DB_HOST}:5432:${SRC_DB_NAME}:${SRC_DB_USER}:${SRC_DB_PASS}" > ~/.pgpass
-      echo "${DST_DB_HOST}:5432:${DST_DB_NAME}:${DST_DB_USER}:${DST_DB_PASS}" >> ~/.pgpass
-      chmod 0600 ~/.pgpass
-      set -x
+    echo "${SRC_DB_HOST}:5432:${SRC_DB_NAME}:${SRC_DB_USER}:${SRC_DB_PASS}" > ~/.pgpass
+    echo "${DST_DB_HOST}:5432:${DST_DB_NAME}:${DST_DB_USER}:${DST_DB_PASS}" >> ~/.pgpass
+    chmod 0600 ~/.pgpass
+    set -x
 
-      pg_dump --jobs=4 --host="$SRC_DB_HOST" --username="$SRC_DB_USER" --dbname="$SRC_DB_NAME" --no-owner --no-privileges --verbose --format=directory --file=/tmp/db-dump 2> >(tee /tmp/error.log >&2)
-      pg_restore --jobs=4 --host="$DST_DB_HOST" --username="$DST_DB_USER" --dbname="$DST_DB_NAME" --clean --if-exists --no-owner --no-privileges --verbose /tmp/db-dump 2> >(tee /tmp/error.log >&2)
-      rm -rv /tmp/db-dump ~/.pgpass
-    } || ERROR_MSG=$(tail -n 10 /tmp/error.log)
+    # Dump the source database
+    pg_dump --jobs=4 --host="$SRC_DB_HOST" --username="$SRC_DB_USER" --dbname="$SRC_DB_NAME" --no-owner --no-privileges --verbose --format=directory --file=~/db-dump 2> >(tee ~/error.log >&2)
+
+    # Drop the destination database
+    dropdb -w --host="$DST_DB_HOST" --username="$DST_DB_USER" "$DST_DB_NAME" --if-exists
+
+    # Create the destination database
+    createdb -w --host="$DST_DB_HOST" --username="$DST_DB_USER" "$DST_DB_NAME"
+
+    # Restore the source database dump to the destination database
+    pg_restore --jobs=4 --host="$DST_DB_HOST" --username="$DST_DB_USER" --dbname="$DST_DB_NAME" --no-owner --no-privileges --verbose ~/db-dump 2> >(tee ~/error.log >&2)
+    rm -rv ~db-dump ~/.pgpass
 
 ---
 apiVersion: batch/v1
@@ -43,7 +48,7 @@ spec:
     spec:
       containers:
       - name: refresh-db
-        image: postgres:14
+        image: ghcr.io/ministryofjustice/hmpps-delius-alfresco-db-utils:nit-1403-alfresco-move-away-from-long-running-github-workflows-10112892047
         imagePullPolicy: IfNotPresent
         resources:
           limits:
